import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Ha Ha Fonny <a href="https://www.youtube.com/watch?v=xvFZjo5PgG0">meymey</a> (👈🏻 click)
        </h1>
  <h1>Roll no. - 2101331520105
            </h1>

        
      </main>

     
    </div>
  )
}
